### ISSUE TITLE
Improve GitLab Pipeline widget

### ISSUE THREAD

**Issue by Tolrod22** [michelin/suricate-widgets#27]
Currently, if a pipeline is yellow (passed with warnings), the widget is green. Suggested improvements:

- yellow background when pipeline is passed with warnings

- add a checkbox in the widget params to show/hide the name of failed jobs (will add a gitlab api request to get the jobs, not given by the pipelines api)

- add a checkbox in the widget params to show/hide the time table (pipeline duration + queued for), as there are already a lot of info shown by this widget

@loicgreffier if you validate the 3 above points, I can implement them

**Comment by loicgreffier** [comment]
Hi @Tolrod22, 

OK for the 3 points above.

For "passed with warning":
- does the GitLab API return a dedicated status for this ? 
- if possible, use the color hex of the "passed with warning" badge (something like #F3B26B)

**Comment by Tolrod22** [comment]
PR opened: https://github.com/michelin/suricate-widgets/pull/28 :)

**Comment by Tolrod22** [comment]
Hello @loicgreffier 

Just spotted an issue today (sorry for that). Opened a new PR to fix it #29
